BEGIN;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    password_hash VARCHAR(256) NOT NULL,
    role VARCHAR(16) NOT NULL DEFAULT 'rider'
        CHECK (role IN ('rider', 'driver', 'admin')),
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_online BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX ix_users_email ON users (email);

CREATE TABLE vehicles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    license_plate VARCHAR(24) NOT NULL UNIQUE,
    make_model VARCHAR(120) NOT NULL,
    capacity INTEGER NOT NULL CHECK (capacity BETWEEN 1 AND 8),
    verification_status VARCHAR(16) NOT NULL DEFAULT 'pending'
        CHECK (verification_status IN ('pending', 'verified', 'rejected')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX ix_vehicles_driver_id ON vehicles (driver_id);

CREATE TABLE rides (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    driver_id INTEGER REFERENCES users(id) ON DELETE RESTRICT,
    pickup VARCHAR(255) NOT NULL,
    dropoff VARCHAR(255) NOT NULL,
    pickup_latitude DOUBLE PRECISION NOT NULL CHECK (pickup_latitude BETWEEN -90 AND 90),
    pickup_longitude DOUBLE PRECISION NOT NULL CHECK (pickup_longitude BETWEEN -180 AND 180),
    dropoff_latitude DOUBLE PRECISION CHECK (dropoff_latitude BETWEEN -90 AND 90),
    dropoff_longitude DOUBLE PRECISION CHECK (dropoff_longitude BETWEEN -180 AND 180),
    passenger_count INTEGER NOT NULL CHECK (passenger_count BETWEEN 1 AND 8),
    fare_amount NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (fare_amount >= 0),
    status VARCHAR(16) NOT NULL DEFAULT 'requested'
        CHECK (status IN ('requested', 'accepted', 'in_transit', 'completed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    accepted_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK ((dropoff_latitude IS NULL) = (dropoff_longitude IS NULL))
);
CREATE INDEX ix_rides_rider_id ON rides (rider_id);
CREATE INDEX ix_rides_driver_id ON rides (driver_id);
CREATE INDEX ix_rides_dispatch ON rides (status, created_at);
CREATE UNIQUE INDEX uq_one_active_ride_per_driver
    ON rides (driver_id)
    WHERE driver_id IS NOT NULL AND status IN ('accepted', 'in_transit');

CREATE TABLE locations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX ix_locations_updated_at ON locations (updated_at);
CREATE INDEX ix_locations_coordinates ON locations (latitude, longitude);

CREATE TABLE ride_declines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id INTEGER NOT NULL REFERENCES rides(id) ON DELETE CASCADE,
    driver_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ride_decline UNIQUE (ride_id, driver_id)
);

COMMIT;
